Projet_Serveur/Models/Produit.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Data.Entity;
using System.Data.SqlTypes;
using System.Linq;
using System.Web;

namespace Projet_Serveur.Models
{
/*On définit ici tous les attributs d'un Produit*/
    public class Produit
    {
        public int ID { get; set; }
        public string NomProduit { get; set; }
        public string Description { get; set; }
        public int QuantiteDispo { get; set; }
        public string Categorie { get; set; }
        public float Cout { get; set; }
        public byte[] Image { get; set; }

    }
/*Création du dbContext*/
    public class ProduitDBContext : DbContext
    {
        public DbSet<Produit> Produits { get; set; }
    }
}

Projet_Serveur/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Projet_Serveur.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

Projet_Serveur/Controllers/ProduitsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Projet_Serveur.Models;

namespace Projet_Serveur.Controllers
{
    public class ProduitsController : Controller
    {
        private ProduitDBContext db = new ProduitDBContext();

        
        public ActionResult Index(string searchString)
        {
            /*Récupérer les produits*/
            var produits = from s in db.Produits
                           select s;
            /*Récuperer seulement une partie des produits*/
            if (!String.IsNullOrEmpty(searchString))
            {
                produits = produits.Where(s => (s.Categorie.Contains(searchString) || s.NomProduit.Contains(searchString)));

                produits = produits.OrderByDescending(s => s.NomProduit);
            }
            return View(produits.ToList());
        }

        public ActionResult IndexAdmin(string searchString)
        {

            var produits = from s in db.Produits
                           select s;
            if (!String.IsNullOrEmpty(searchString))
            {
                produits = produits.Where(s => (s.Categorie.Contains(searchString) || s.NomProduit.Contains(searchString)));

                produits = produits.OrderByDescending(s => s.NomProduit);
            }
            return View(produits.ToList());
        }

        // Récupèrer le détail d'un produit passé en parametre
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produit produit = db.Produits.Find(id);
            if (produit == null)
            {
                return HttpNotFound();
            }
            return View(produit);
        }

        // Créer un produit
        public ActionResult Create()
        {
            return View();
        }

        // POST: Produits/Create
        // Afin de déjouer les attaques par survalidation, activez les propriétés spécifiques auxquelles vous voulez établir une liaison. Pour 
        // plus de détails, consultez https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,NomProduit,Description,QuantiteDispo,Categorie,Cout,Image")] Produit produit)
        {
            if (ModelState.IsValid)
            {
                db.Produits.Add(produit);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(produit);

        }

        // Modifier un produit passé en paramètre
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produit produit = db.Produits.Find(id);
            if (produit == null)
            {
                return HttpNotFound();
            }
            return View(produit);
        }

        // Modifier un produit avec la méthode post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,NomProduit,Description,QuantiteDispo,Categorie,Cout,Image")] Produit produit)
        {
            if (ModelState.IsValid)
            {
                db.Entry(produit).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("IndexAdmin");
            }
            return View(produit);
        }

        // Supprimer un produit
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Produit produit = db.Produits.Find(id);
            if (produit == null)
            {
                return HttpNotFound();
            }
            return View(produit);
        }

            /*Ajouter un produit au panier*/
        public ActionResult AjouterAuPanier(Produit produit)
        {
            if (produit == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else
            {
            

                // Créer le panier s'il n'existe pas encore
                if (Session["panier"] == null)
                {
                    List<Produit>panier = new List<Produit>();
                    panier.Add((Produit)produit);
                    Session["panier"] = panier;
                }
                /*Sinon on récupère la liste et on y ajouter le produit*/
                else
                {
                    List<Produit> panier = (List<Produit>)Session["panier"];
                    panier.Add((Produit)produit);
                }
                /*Pour gérer l'affichage du feedback*/
                TempData["message"] = "L'article a bien été ajouté au panier";
                return RedirectToAction("Index");
            }
            
}
            /*Retirer un produit du panier*/
        public ActionResult RetirerDuPanier(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            else {
                /*On parcours la liste jusqu'au produit souhaité et on le retire*/
                List<Produit> panier = (List<Produit>)Session["panier"];
                int i = 0;
                foreach (Produit produit in panier)
                {
                    if(produit.ID == id)
                    {
                        break;
                    }
                    else
                    {
                        i++;
                    }
                }
                panier.RemoveAt(i);
                Session.Remove("panier");
                if(panier.Count > 0)
                {
                    Session["panier"] = panier;
                }
            }
                /*Pour gérer le feedback*/
            TempData["message"] = "L'article a bien été retiré du panier";
            return RedirectToAction("Index");
        }


        // Supprimer un produit avec la méthode post
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Produit produit = db.Produits.Find(id);
            db.Produits.Remove(produit);
            db.SaveChanges();
            return RedirectToAction("IndexAdmin");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Projet_Serveur/Controllers/UniversController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Projet_Serveur.Controllers
{
    public class UniversController : Controller
    {
        // On retourne la vue notre univers
        public ActionResult Index()
        {
            return View("Index");
        }
    }
}

Projet_Serveur/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

@*<div class="jumbotron">
        <h1 class="display-4">Actualités</h1>
        <hr class="my-4">
        <p class="lead">Nouvelle gamme peaux sèches</p>
        <p>Découvrez notre nouvelle gamme spécifiquement concue pour les peaux sèches.</p>
        <p class="lead">
            <a class="btn btn-primary btn-lg" href="#" role="button">Cliquez ici pour découvrir</a>
        </p>
    </div>*@



<div class="row bg-primary">
    <div class="m-3">
        <h1 class="">Actualités</h1>

        <div class="col-md-4">
            <img class="mr-3" src="~/Images/nouvelleGamme.jpg" alt="h" width="210" height="180" />
        </div>

        <div class="col-md-8">
            <h2> Nouvelle gamme peaux sèches</h2>
            <p>Découvrez notre nouvelle gamme spécifiquement concue pour les peaux sèches.</p>
            <p><a class="btn btn-default btn-info" href="" style="background-color:slateblue; color:white; border-color:slateblue">Cliquez ici pour découvrir</a></p>
        </div>
    </div>
</div>




<div class="row">
    <h1 class="mt-3">Nos magasins</h1>

    <div class="col-md-4 table-hover">
        <h2>Boutique Joseph-Vallier</h2>
        <img class="mr-3" src="/Images/institut.jpg" width="320" height="150"/>
        <p>
            Venez découvrir toutes nos gammes dans la plus grande boutique de BautySphere au 3 rue Joseph-Vallier. Vous pourrez également consulter les soins disponibles en institut, prendre endez-vous et demander conseil à nos vendeuses.
        </p>
    </div>

    <div class="col-md-4">
        <h2>Institut Lafayette</h2>
        <img class="mr-3" src="/Images/Institut1.jpg" width="320" height="150"/>
        <p>
            Une large gamme de soins vous est proposé par nos experts beauté. Venez demander conseil, vous faire maquiller, masser et bien plus dans l'institut Lafayette au 56 place Grenette'. Prenez rendez-vous en boutique !
        </p>
    </div>
    <div class="col-md-4">
        <h2>Boutique Championnet</h2>
        <img class="mr-3" src="/Images/Institut1.jpg" width="320" height="150" />
        <p>Découvrez les gammes classique de BeautySphere et prenez rendez-vous pour vos soins en institut au 6 Rue Lakanal quartier Championnet.</p>
    </div>
</div>

Projet_Serveur/Views/Produits.cshtml
@{
    ViewBag.Title = "Produits";
}

<h2>Produits</h2>

Projet_Serveur/Views/Produits/Create.cshtml
@model Projet_Serveur.Models.Produit

@{
    ViewBag.Title = "Create";
}

<h2>Liste des produits</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="form-horizontal">
        <h4>Produit</h4>
        <hr />
            @*Ici on va avoir pour chaque attribut de l'objet à ajouter à la base de données un éditeur et un validateur*@
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NomProduit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomProduit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NomProduit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QuantiteDispo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuantiteDispo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QuantiteDispo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Categorie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Categorie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Categorie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cout, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cout, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cout, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Image, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.TextBoxFor(model => model.Image, new { type = "file" })
                @Html.ValidationMessageFor(model => model.Image)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retourner à la vue admin", "IndexAdmin")
</div>

Projet_Serveur/Views/Produits/Delete.cshtml
@model Projet_Serveur.Models.Produit

@{
    ViewBag.Title = "Supprimer";
}

<h2>Supprimer un produit</h2>

<h3>Voulez-vous vraiment supprimer ce produit ?</h3>
<div>
@*On affiche simplement les détails du produit et on propose de le supprimer*@
    <h4>Produit</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NomProduit)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NomProduit)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QuantiteDispo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.QuantiteDispo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Categorie)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Categorie)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Cout)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Cout)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Supprimer" class="btn btn-default" /> |
            @Html.ActionLink("Retourner à la vue amdin", "IndexAdmin")
        </div>
    }
</div>

Projet_Serveur/Views/Produits/Details.cshtml
@model Projet_Serveur.Models.Produit

@{
    ViewBag.Title = "Details";
}
@*Vue lorsqu'on accède à un détail du produit*@
<div class="productContainer">
    <div class="row">
        <div class="col-lg-6" id="imgContainer">
            <img class="imgProduit" src="/Images/produit.png" alt="product picture not found"></img>
        </div>
        <div class="col-lg-6">
            <h2>@Html.DisplayFor(model => model.NomProduit)</h2>
            <p class="prixProduit">@Html.DisplayFor(model => model.Cout) €</p>
            <p>@Html.DisplayFor(model => model.Description)</p>
            @*Bouton d'ajout au panier qui ajoute le produit this*@
            @Html.ActionLink("Ajouter au panier", "AjouterAuPanier", this.Model,
        htmlAttributes: new { @class = "btn btn-primary", @width = "fit-content" })
            @Html.ActionLink("Retourner à la liste", "Index", "Produits",
        htmlAttributes: new { @class = "btn btn-secondary", @width = "fit-content" })

        </div>
    </div>
</div>

Projet_Serveur/Views/Produits/Edit.cshtml
@model Projet_Serveur.Models.Produit

@{
    ViewBag.Title = "Modifier";
}

<h2>Modifier un produit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    @*Comme pour le créer, cependant ici on part déjà avec des valeurs de base dans les éditeurs*@
    <div class="form-horizontal">
        <h4>Produit</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.NomProduit, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NomProduit, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NomProduit, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QuantiteDispo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QuantiteDispo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QuantiteDispo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Categorie, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Categorie, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Categorie, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Cout, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Cout, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Cout, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Enregistrer" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Retourner à vue admin", "IndexAdmin")
</div>

Projet_Serveur/Views/Produits/Index.cshtml
@model IEnumerable<Projet_Serveur.Models.Produit>
@{
    ViewBag.Title = "Home Page";
}


<div class="container">
@*On gère l'affichage de la div de feedback si le tempdata message n'est pas null*@
    @if (TempData["message"] != null)
    {
        <div id="check"></div>
        <script>
                    document.getElementById("check").innerHTML = ('@TempData["message"]');
                    //ADD THIS CODE
                    setTimeout(function () {
                        document.getElementById("check").innerHTML = "";
                    }, 3000);</script>
    }
    <h1 class="selectedCat">Tous nos produits</h1>

    <div class="col-md-3 filterBox">
        <h2>Filtres</h2>
        <h3>Catégorie</h3>
            @*Gestion des filtres*@
        @using (Html.BeginForm("Index", "Produits"))
        {


            <label class="container">
                <input type="radio" id="SearchString" name="SearchString" value="visage">
                Visage
            </label>

            <label class="container">
                <input type="radio" id="SearchString" name="SearchString" value="Corps">
                Corps
            </label>

            <label class="container">
                <input type="radio" id="SearchString" name="SearchString" value="Cheveux">
                Cheveux
            </label>
            <input type="submit" value="Filtrer" class="btn btn-primary" />
        }


    </div>
@*On affiche chaque produit*@
    @foreach (var item in Model)
    {
        <div class="templateProduct col-md-3 col-lg-offset-0.5">
            <img src="/Images/produit.png" width="150" height="150" />
            <h3>
                @Html.ActionLink(item.NomProduit, "Details", new { id = item.ID },
             htmlAttributes: new { @style = "color:black" })
        </h3>
        <p>
            @Html.DisplayFor(modelItem => item.Cout) € - @Html.ActionLink("Ajouter au panier", "AjouterAuPanier", item,
htmlAttributes: new { @style = "color:black" })
        </p>
    </div>
}

</div>

Projet_Serveur/Views/Produits/IndexAdmin.cshtml
@model IEnumerable<Projet_Serveur.Models.Produit>

@{
    ViewBag.Title = "Index";
}

<h2>Gérer les produits</h2>
@*Vue dans laquelle on gère les produits*@

<p>
    @Html.ActionLink("Ajouter un produit", "Create")
</p>
@using (Html.BeginForm())
{
    <p>
        Rechercher: @Html.TextBox("SearchString")
        <input type="submit" value="Rechercher" />
    </p>
}


    @foreach (var item in Model)
    {
        <div>
            <h4>@item.NomProduit </h4>
            @Html.ActionLink("Modifier", "Edit", new { id = item.ID }) |
            @Html.ActionLink("Supprimer", "Delete", new { id = item.ID })
            
        </div>
    }

Projet_Serveur/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mon application ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse" title="more options">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("BeautySphere", "", "", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*Les différents objets de la barre*@
                    <li>@Html.ActionLink("Boutique", "", "Produits")</li>
                    <li>@Html.ActionLink("Notre univers", "", "Univers")</li>
                    <li>@Html.ActionLink("Accéder à la partie admin", "IndexAdmin", "Produits")</li>

                    <div class="rightItems">
                    <li>
                        @using (Html.BeginForm("Index", "Produits"))
                        {@Html.TextBox("SearchString")<input type="submit" value="Rechercher" />}
                    </li>
                    <li>
                        <button type="button" class="btn btn-primary mt-10" data-toggle="modal" data-target="#form" style="margin-left: 10px">
                            Panier
                        </button>
                    </li>
                    </div>

            </ul>
        </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - BeautySphere</p>
            
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>


@*La modale du panier*@
<div class="modal fade" id="form" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true" style="display: none;">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h3 class="modal-title" id="exampleModalLabel">Mon panier</h3>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <form>
                <div class="modal-body">
                    @if (Session["panier"] != null)
                    {
                        var coutTotal = new float();
                        coutTotal = 0;
                        <table id="tableau_modale">
                            <tr id="entete_tableau_modale">
                                <th colspan="2">Produit</th>
                                <th colspan="2" width="50%">Prix</th>
                            </tr>
                                @*Affichage de tous les produits du panier*@
                            @foreach (Projet_Serveur.Models.Produit produit in (List<Projet_Serveur.Models.Produit>)Session["panier"])
                            {
                                <tr>
                                    <td style="width:75px;">
                                        <img src="/Images/produit.png" width="75" height="75" />
                                    </td>
                                    <td>
                                        @produit.NomProduit
                                    </td>
                                    <td>
                                        @produit.Cout €
                                    </td>
                                    <td>
                                        @Html.ActionLink("Retirer", "RetirerDuPanier", new { id = produit.ID })
                                    </td>
                                </tr>
                                coutTotal += produit.Cout;
                            }
                            <tr>
                                <td>

                                </td>
                                <td>

                                </td>
                                <td>
                                    <b>Coût total : @coutTotal €</b>
                                </td>
                                <td>
                                    
                                </td>
                            </tr>
                        </table>
                    }
                    else
                    {
                        <span>Votre panier est vide !</span>
                    }
                </div>
                <div class="modal-footer border-top-0 d-flex justify-content-center">
                    @if (Session["panier"] != null)
                    {
                        <button type="submit" class="btn btn-primary">Procéder au paiement</button>

                    }
                    else
                    {
                        <button type="submit" class="btn btn-primary">Continuer mes achats</button>

                    }
                    
                </div>
            </form>
        </div>
    </div>
</div>

Projet_Serveur/Views/Univers/Index.cshtml
<div class="container">
    <div class="universHeader">
        <h1 class="selectedCat" id="universTitre">Notre univers</h1>
    </div>
    <div class="row">
        <h2></h2>
        <p>Bienvenue sur le site de BeautySphere, un espace bien être vous proposant ses produits de beauté et ses différents services en institut. Venez découvrir les gammes de soins capillaires, soins pour le visage et pour le corps dans nos boutiques. Venez rencontrer des experts beauté et obtenir des conseils pour prendre soin de votre peu et vos cheveux. Un grand choix de services vous sera proposé dans nos instituts pour un moment de bien être. Prenez rendez-vous en boutique ou en institut pour un massage, une manucure, une épilation et bien plus.</p>

    </div>

    <div class="row" id="confiance">
        <h2>Ils nous font confiance</h2>
        <div class="col-lg-3">
            <h3>Laura C.</h3>
            <p>Merci mille fois pour cette superbe expérience. Un merveilleux moment de calme et de détente grâce à l'équipe de l'institut Lafayette. Je  reviendrai !</p>
            <p>5 étoiles</p>
        </div>
        <div class="col-lg-3">
            <h3>Coalie V.</h3>
            <p>Merci mille fois pour cette superbe expérience. Un merveilleux moment de calme et de détente grâce à l'équipe de l'institut Lafayette. Je  reviendrai !</p>
            <p>5 étoiles</p>
        </div>
        <div class="col-lg-3">
            <h3>Solène H.</h3>
            <p>Merci mille fois pour cette superbe expérience. Un merveilleux moment de calme et de détente grâce à l'équipe de l'institut Lafayette. Je  reviendrai !</p>
            <p>5 étoiles</p>
        </div>
        <div class="col-lg-3">
            <h3>Nina I.</h3>
            <p>Merci mille fois pour cette superbe expérience. Un merveilleux moment de calme et de détente grâce à l'équipe de l'institut Lafayette. Je  reviendrai !</p>
            <p>5 étoiles</p>
        </div>
    </div>
</div>